# -*- coding: utf-8 -*-
"""ExtractAudioFromVideo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geb3iKg4C9xBAiCMGyu2pGXfSIpsFJ1j
"""

# Import moviepy
from moviepy.editor import VideoFileClip


def extract_audio(path:str):
  video =  VideoFileClip(path.strip())
  audio = video.audio
  audio=audio.set_duration(600.00)
  audio.duration
  audio.write_audiofile("./audio.mp3")
